// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sa3dny.Data;

#nullable disable

namespace Sa3dny.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Admin", b =>
                {
                    b.Property<int>("Admin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_ID"));

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Admin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_ID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Customer", b =>
                {
                    b.Property<Guid>("Id_Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernorateId_Governorate")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId_Location")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Customer");

                    b.HasIndex("GovernorateId_Governorate");

                    b.HasIndex("LocationId_Location");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Edu_Service", b =>
                {
                    b.Property<Guid>("Service_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Service_Id");

                    b.ToTable("Edu_Services");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Governorate", b =>
                {
                    b.Property<int>("Id_Governorate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Governorate"));

                    b.Property<string>("Name_Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Governorate");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id_Governorate = 1,
                            Name_Governorate = "Cairo"
                        },
                        new
                        {
                            Id_Governorate = 2,
                            Name_Governorate = "Giza"
                        },
                        new
                        {
                            Id_Governorate = 3,
                            Name_Governorate = "Alexandria"
                        },
                        new
                        {
                            Id_Governorate = 4,
                            Name_Governorate = "Assiut"
                        },
                        new
                        {
                            Id_Governorate = 5,
                            Name_Governorate = "Aswan"
                        },
                        new
                        {
                            Id_Governorate = 6,
                            Name_Governorate = "Luxor"
                        },
                        new
                        {
                            Id_Governorate = 7,
                            Name_Governorate = "Sohag"
                        },
                        new
                        {
                            Id_Governorate = 8,
                            Name_Governorate = "Qena"
                        },
                        new
                        {
                            Id_Governorate = 9,
                            Name_Governorate = "Minya"
                        },
                        new
                        {
                            Id_Governorate = 10,
                            Name_Governorate = "Beni Suef"
                        },
                        new
                        {
                            Id_Governorate = 11,
                            Name_Governorate = "Fayoum"
                        },
                        new
                        {
                            Id_Governorate = 12,
                            Name_Governorate = "Dakahlia"
                        },
                        new
                        {
                            Id_Governorate = 13,
                            Name_Governorate = "Sharqia"
                        },
                        new
                        {
                            Id_Governorate = 14,
                            Name_Governorate = "Gharbia"
                        },
                        new
                        {
                            Id_Governorate = 15,
                            Name_Governorate = "Monufia"
                        },
                        new
                        {
                            Id_Governorate = 16,
                            Name_Governorate = "Qalyubia"
                        },
                        new
                        {
                            Id_Governorate = 17,
                            Name_Governorate = "Kafr El Sheikh"
                        },
                        new
                        {
                            Id_Governorate = 18,
                            Name_Governorate = "Beheira"
                        },
                        new
                        {
                            Id_Governorate = 19,
                            Name_Governorate = "Damietta"
                        },
                        new
                        {
                            Id_Governorate = 20,
                            Name_Governorate = "Port Said"
                        },
                        new
                        {
                            Id_Governorate = 21,
                            Name_Governorate = "Ismailia"
                        },
                        new
                        {
                            Id_Governorate = 22,
                            Name_Governorate = "Suez"
                        },
                        new
                        {
                            Id_Governorate = 23,
                            Name_Governorate = "North Sinai"
                        },
                        new
                        {
                            Id_Governorate = 24,
                            Name_Governorate = "South Sinai"
                        },
                        new
                        {
                            Id_Governorate = 25,
                            Name_Governorate = "Red Sea"
                        },
                        new
                        {
                            Id_Governorate = 26,
                            Name_Governorate = "New Valley"
                        },
                        new
                        {
                            Id_Governorate = 27,
                            Name_Governorate = "Matruh"
                        });
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Home_Service", b =>
                {
                    b.Property<Guid>("Service_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Service_Id");

                    b.ToTable("Home_Services");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Location", b =>
                {
                    b.Property<int>("Id_Location")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Location"));

                    b.Property<int?>("GovernorateId_Governorate")
                        .HasColumnType("int");

                    b.Property<string>("Name_Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Location");

                    b.HasIndex("GovernorateId_Governorate");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id_Location = 1,
                            Name_Location = "Ferial"
                        },
                        new
                        {
                            Id_Location = 2,
                            Name_Location = "Mousna3 Sayed"
                        },
                        new
                        {
                            Id_Location = 3,
                            Name_Location = "Governorate Street"
                        },
                        new
                        {
                            Id_Location = 4,
                            Name_Location = "Libraries"
                        },
                        new
                        {
                            Id_Location = 5,
                            Name_Location = "Asmaa Allah Square"
                        },
                        new
                        {
                            Id_Location = 6,
                            Name_Location = "Station"
                        },
                        new
                        {
                            Id_Location = 7,
                            Name_Location = "Fateh"
                        },
                        new
                        {
                            Id_Location = 8,
                            Name_Location = "Hamraa"
                        });
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Provider", b =>
                {
                    b.Property<Guid>("provider_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIdImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ProfessionalLicensePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("national_id_Provider")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<double?>("rate_Provider")
                        .HasColumnType("float");

                    b.HasKey("provider_id");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ProviderOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequestId");

                    b.ToTable("ProviderOffers");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Provider_Service", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProviderId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Provider_Services");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Requests", b =>
                {
                    b.Property<Guid>("Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Customer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description_Req")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Provider_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Service_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Total_Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.HasKey("Request_Id");

                    b.HasIndex("AcceptedOfferId");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("Provider_Id");

                    b.HasIndex("Service_Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Review_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Customer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Provider_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<Guid>("Request_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Review_Id");

                    b.HasIndex("Customer_Id");

                    b.HasIndex("Provider_Id");

                    b.HasIndex("Request_Id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Service", b =>
                {
                    b.Property<Guid>("service_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Min_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ServiceCategoryId_Category")
                        .HasColumnType("int");

                    b.Property<string>("service_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("service_id");

                    b.HasIndex("ServiceCategoryId_Category");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            service_id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Home cleaning service",
                            Min_price = 0m,
                            service_name = "Cleaning"
                        },
                        new
                        {
                            service_id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Plumbing service",
                            Min_price = 0m,
                            service_name = "Plumbing"
                        },
                        new
                        {
                            service_id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Electrical service",
                            Min_price = 0m,
                            service_name = "Electricity"
                        },
                        new
                        {
                            service_id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Carpentry service",
                            Min_price = 0m,
                            service_name = "Carpentry"
                        },
                        new
                        {
                            service_id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Word and report writing",
                            Min_price = 0m,
                            service_name = "Word / Report"
                        },
                        new
                        {
                            service_id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Presentation design",
                            Min_price = 0m,
                            service_name = "Presentation"
                        },
                        new
                        {
                            service_id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Excel sheets service",
                            Min_price = 0m,
                            service_name = "Excel"
                        },
                        new
                        {
                            service_id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "CV writing service",
                            Min_price = 0m,
                            service_name = "CV Creation"
                        },
                        new
                        {
                            service_id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Nursing at home",
                            Min_price = 0m,
                            service_name = "Home Nursing"
                        },
                        new
                        {
                            service_id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Description = "Doctor home visit",
                            Min_price = 0m,
                            service_name = "Doctor Visit"
                        },
                        new
                        {
                            service_id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Description = "Injection at home",
                            Min_price = 0m,
                            service_name = "Injection Service"
                        },
                        new
                        {
                            service_id = new Guid("13131313-1313-1313-1313-131313131313"),
                            Description = "Medical follow-up",
                            Min_price = 0m,
                            service_name = "Follow-up"
                        });
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Category"));

                    b.Property<string>("Name_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Category");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id_Category = 1,
                            Name_Category = "Home Services"
                        },
                        new
                        {
                            Id_Category = 2,
                            Name_Category = "Educational Services"
                        },
                        new
                        {
                            Id_Category = 3,
                            Name_Category = "Healthcare Services"
                        });
                });

            modelBuilder.Entity("Sa3dny.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ChatMessage", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Requests", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Customer", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Governorate", null)
                        .WithMany("Customers")
                        .HasForeignKey("GovernorateId_Governorate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sa3dny.Data.Models.Location", null)
                        .WithMany("Customers")
                        .HasForeignKey("LocationId_Location")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Sa3dny.Data.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Edu_Service", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Service", "service")
                        .WithMany()
                        .HasForeignKey("Service_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Home_Service", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Service", "service")
                        .WithMany()
                        .HasForeignKey("Service_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("service");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Location", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Governorate", null)
                        .WithMany("Locations")
                        .HasForeignKey("GovernorateId_Governorate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Provider", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Governorate", "Governorate")
                        .WithMany("Providers")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.ServiceCategory", "ServiceCategory")
                        .WithMany("Providers")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Sa3dny.Data.Models.Provider", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");

                    b.Navigation("Service");

                    b.Navigation("ServiceCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ProviderOffer", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Requests", "Request")
                        .WithMany("Offers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Provider_Service", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Provider", "Provider")
                        .WithMany("provider_Services")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Service", "Service")
                        .WithMany("provider_services")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Requests", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.ProviderOffer", "AcceptedOffer")
                        .WithMany()
                        .HasForeignKey("AcceptedOfferId");

                    b.HasOne("Sa3dny.Data.Models.Customer", "customer")
                        .WithMany("requests")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Provider", "provider")
                        .WithMany("requests")
                        .HasForeignKey("Provider_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sa3dny.Data.Models.Service", "service")
                        .WithMany("requests")
                        .HasForeignKey("Service_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcceptedOffer");

                    b.Navigation("customer");

                    b.Navigation("provider");

                    b.Navigation("service");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Review", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Customer", "customer")
                        .WithMany("reviews")
                        .HasForeignKey("Customer_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Provider", "provider")
                        .WithMany("reviews")
                        .HasForeignKey("Provider_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.Requests", "requests")
                        .WithMany("reviews")
                        .HasForeignKey("Request_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("provider");

                    b.Navigation("requests");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Service", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.ServiceCategory", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId_Category")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sa3dny.Models.Notification", b =>
                {
                    b.HasOne("Sa3dny.Data.Models.Requests", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sa3dny.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Customer", b =>
                {
                    b.Navigation("requests");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Governorate", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Locations");

                    b.Navigation("Providers");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Location", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Provider", b =>
                {
                    b.Navigation("provider_Services");

                    b.Navigation("requests");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Requests", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.Service", b =>
                {
                    b.Navigation("provider_services");

                    b.Navigation("requests");
                });

            modelBuilder.Entity("Sa3dny.Data.Models.ServiceCategory", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
